### ISSUE TITLE
Resolve JanuaryTests dependency

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#11]
At the moment running tests is dependent on having https://github.com/jonahkichwacoders/JanuaryTests cloned into $HOME.

JanuaryTests was derived from ICETests maintained by @jayjaybillings. 

We either need to inline these test resources into January or file a CQ to have the dependency.

**Comment by jonahkichwacoders** [comment]
These test resources are not part of the January release.

**Comment by PeterC-DLS** [comment]
No longer an issue as january-forms was moved to https://github.com/eclipse/january-forms/
