### ISSUE TITLE
January should support slice streams

### ISSUE THREAD

**Issue by gerring** [eclipse/january#118]
There should be a functional interface in addition to things like PositionIterator. The .stream() and .forEach() method should probably be available on any dataset (might need some input, so might not be a pure lambda). It will take some thinking about how to marry the idea of a stream with things like the slice iterator. This should not be insurmountable. Will ponder and suggest some changes. 

Functional interfaces would allow code to iterate datasets and to be parallel simply by calling the .parallel() or .parallelStream(). This should enable parallel speedups to be quantified without recoding the operation.

**Comment by PeterC-DLS** [comment]
Putting these methods will break Java 1.7 compatibility.

I suggest that we add static helper methods in another plugin. See the https://github.com/eclipse/dawnsci/pull/543

**Comment by gerring** [comment]
I don't think this is an issue. The 2.0 branch can continue to be 1.7 while we start lambda stuff with master. Everyone should be happy with that.

**Comment by PeterC-DLS** [comment]
That increases our maintenance load.

**Comment by gerring** [comment]
No it doesn't we already have that branch!

**Comment by gerring** [comment]
final ILazyDataset lz = Random.lazyRand(64, 64, 100, 100);      

I hacked up streams for slicing so you can replace something like:
           final PositionIterator it = new PositionIterator(new int[]{64, 64});
           final List<Number> maxes = new ArrayList<Number>();
           while(it.hasNext()) {
                int[] pos = it.getPos();
                Slice[] slice = new Slice[lz.getRank()];
                for (int i = 0; i < pos.length; i++) {
                     slice[i] = new Slice(pos[i], pos[i]+1);
                }
                IDataset image = lz.getSlice(slice);
                maxes.add(image.max());
           }

With this:
           List<Number> maxes = lz.positionStream(64, 64).map(set->set.max()).collect(Collectors.toList());

I find this desirable because I can never remember how to slice correctly, streams give a great alternative.

**Comment by jonahkichwacoders** [comment]
> No it doesn't we already have that branch!

Maintenance is much more than having a branch. How long do you envision supporting Java 7 for? As long as Java 7 is supported we would need two branches to be active, both receiving bug fixes, etc. We just downgraded to Java 7....

**Comment by gerring** [comment]
Replaced with https://github.com/eclipse/january/issues/156
