### ISSUE TITLE
Generate javadocs for build and publish them

### ISSUE THREAD

**Issue by PeterC-DLS** [eclipse/january#125]
Need to add `tycho-document-bundle-plugin` from `org.eclipse.tycho.extras`. Maybe host them on `github.io` too.

**Comment by jonahkichwacoders** [comment]
@PeterC-DLS are you doing this? Feel free to assign to me if not.

**Comment by PeterC-DLS** [comment]
Have you done this before? If so, it will be a lot quicker :-)

**Comment by jonahkichwacoders** [comment]
No I haven't, but happy to learn. 

The easiest place to put the javadocs is download.eclipse.org/january (per release/build dir). We could then put most recent version on eclipse.org/january/docs? 

The repo is already in place for https://git.eclipse.org/r/#/admin/projects/www.eclipse.org/january

**Comment by jonahkichwacoders** [comment]
BTW  http://eclipse.org/january/ is just a redirect for now to projects page, but it needn't always be. (see http://git.eclipse.org/c/www.eclipse.org/january.git/tree/index.php)

**Comment by PeterC-DLS** [comment]
Ok, thanks for picking this up.

**Comment by jonahkichwacoders** [comment]
There are a number of javadoc errors that need to be resolved, so this is a two part task. (i.e. lots of > and < in javadocs). For example [Comparisons.java L1575](https://github.com/eclipse/january/blob/9b7b26a91313b5ae28b7c4c64db5b0de822b2d61/org.eclipse.january/src/org/eclipse/january/dataset/Comparisons.java#L1575)

**Comment by jonahkichwacoders** [comment]
I take it back, we may not have to resolve them, at least not yet. The javadocs look reasonable, just lots of errors. We should resolve the errors as it may be that some places the errors/warnings are producing bad HTML. At the moment there are 91 errors and 100 warnings.

**Comment by PeterC-DLS** [comment]
Okay, shall we defer these errors to a later issue? Are these errors available in either CI at the moment?

**Comment by jonahkichwacoders** [comment]
> Okay, shall we defer these errors to a later issue?
Yes

> Are these errors available in either CI at the moment?
No, but they will be soon in the PR.

**Comment by jonahkichwacoders** [comment]
> No, but they will be soon in the PR.

No actually they won't be because we are using javadoc 1.7 and the linting of javadocs is a new feature in Java 8. See #128.

**Comment by jonahkichwacoders** [comment]
"they" --> the errors in the output.

**Comment by jonahkichwacoders** [comment]
Its in the build now [2.0](http://download.eclipse.org/january/builds/january-2.0/latest/apidocs/) [master](http://download.eclipse.org/january/builds/january-master/latest/apidocs/). 

When I release 2.0.1 I will publish the docs on http://www.eclipse.org/january/apidocs

**Comment by jonahkichwacoders** [comment]
I have published the javadocs for the upcoming 2.0.1 release (if there is a change I will update them).

https://eclipse.org/january/apidocs/ -> redirects to https://eclipse.org/january/apidocs/latest/
There is also per version upload https://eclipse.org/january/apidocs/2.0.1/

See [websitre git](http://git.eclipse.org/c/www.eclipse.org/january.git/tree/apidocs?id=90e839cbb8d5bf2bf0a7fea934b29382d55c8366)
