### ISSUE TITLE
Correct Javadoc errors when generating with Java 8

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#128]
(follow on from #125) 

The current javadocs contain many HTML errors when generating with Java 8. e..g `<` in the javadoc. However as we are currently using Java 7 javadoc, these items are not errors. 

The reason we see these errors in Java 8 is because of a new feature: [JEP 172 DocLint](http://openjdk.java.net/jeps/172)

**Comment by jonahkichwacoders** [comment]
There is some useful info about this on http://jdpgrailsdev.github.io/blog/2014/04/03/maven_java8_javadoc.html

**Comment by jonahkichwacoders** [comment]
@PeterC-DLS I have published master apidocs (now done automatically) to http://download.eclipse.org/january/builds/january-master/latest/apidocs/

Can you have a check and see if they are OK.

Some features I added:

* links to all types that we depend on (apache, log4j, oracle): [links](https://github.com/eclipse/january/blob/12d837f31a43d4c885e42c9762b2a1bc56e08544/org.eclipse.january/pom.xml#L79). So for example if you look at [NullStorelessUnivariateStatistic#copy](http://download.eclipse.org/january/builds/january-master/latest/apidocs/org/eclipse/january/dataset/NullStorelessUnivariateStatistic.html#copy()) you'll see the return type links back to the correct version (3.5) of StorelessUnivariateStatistic at apache
* generate API docs only for non-internal: [excludePackageNames](https://github.com/eclipse/january/blob/12d837f31a43d4c885e42c9762b2a1bc56e08544/org.eclipse.january/pom.xml#L77)
* source is generated for easier cross refencing: [linksource](https://github.com/eclipse/january/blob/12d837f31a43d4c885e42c9762b2a1bc56e08544/org.eclipse.january/pom.xml#L78)

I have started the PRs (#127) for 2.0 branch, but I need to bump the versions still. If it looks OK we can do a 2.0.1 RC tomorrow.

**Comment by PeterC-DLS** [comment]
@jonahkichwacoders The docs look very fine - even the maths in Comparisons.Monotonicity. Some of the packages need a bit more overview information (to be added in the future).

**Comment by PeterC-DLS** [comment]
@jonahkichwacoders Cool features for those external links though I think that class should be a private one... Can I assume that being Java 8 compliant is backwardly compatible too?

**Comment by jonahkichwacoders** [comment]
>  Can I assume that being Java 8 compliant is backwardly compatible too?

Yes. What Java 8 added is a linter for javadocs. The linter can be tuned off or we can fix the lint issues. I have always been of two minds about javadocs as I spend 1/2 my time reading them in code and 1/2 in html. Sometimes to make them look nice in html lowers their value in the code.

**Comment by PeterC-DLS** [comment]
Closing as all errors and warnings were fixed in #450
