### ISSUE TITLE
Building with Maven at command line fails on Windows

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#143]
The Maven exec plug-in to ensure that the template generated java files are up to date does not work on WIndows at the moment.

**Comment by yannick-mayeur** [comment]
Error message : 
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (Verify generated files are up to date) on project org.eclipse.january: Command execution failed. Cannot run program "C:\Users\yayam\workspace\january\org.eclipse.january\src\org\eclipse\january\dataset\internal\template\verify_all.sh" (in directory "C:\Users\yayam\workspace\january\org.eclipse.january\src\org\eclipse\january\dataset\internal\template"): CreateProcess error=193, %1 n'est pas une application Win32 valide -> [Help 1]
`

**Comment by PeterC-DLS** [comment]
Fixed in #163
