### ISSUE TITLE
& and && problem

### ISSUE THREAD

**Issue by PierreSachot** [eclipse/january#145]
In some examples like NumPy, the System.out.println display sometimes & and sometimes &&

**Comment by jonahkichwacoders** [comment]
Hi @PeterC-DLS 

@PierreSachot  can fix this up, but I need your comment on this please.

In the Numpy example, sometimes logicalAnd is written as & and sometimes as && in comments/sysouts. In the [Comparisons.logicalAnd javadoc](https://eclipse.org/january/apidocs/2.0.1/org/eclipse/january/dataset/Comparisons.html#logicalAnd(java.lang.Object,%20java.lang.Object)) it is written as && 

So the question is, which is correct? Or is it more complicated.

I previously reject PR #138 on this topic.

Thanks!
Jonah

**Comment by PeterC-DLS** [comment]
No, the Javadoc pertains to matlab as noted [here](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users-notes). So you are correct in rejecting it. Perhaps the print should clarify the January operation...

There's also an issue owing to `Maths.bitwise*` not being supported for output boolean datasets.

Peter
