### ISSUE TITLE
Link to master January project URL

### ISSUE THREAD

**Issue by IanMayo** [eclipse/january#147]
To improve SEO @tracymiranda indicated [1] that the eclipse project [2] is the one that should be referenced from other web-pages, to include the page-rank of that page.

We don't include that link in the January GitHub repo home page (readme).  I'll produce a PR to correct this.

[1]. https://dev.eclipse.org/mhonarc/lists/january-dev/msg00265.html
[2]. https://projects.eclipse.org/projects/science.january

**Comment by jonahkichwacoders** [comment]
Ian, we are currently working on new (first) webpage for https://eclipse.org/january. Can you point there please?

**Comment by jonahkichwacoders** [comment]
The https://eclipse.org/january currently redirects to https://projects.eclipse.org/projects/science.january

**Comment by IanMayo** [comment]
Sure @jonahkichwacoders = on it.
