### ISSUE TITLE
sshape clarification in SliceIterator

### ISSUE THREAD

**Issue by PierreSachot** [eclipse/january#157]
Hi,

I would like to know what is the sshape in the constructor of a SliceIterator.

Thanks.

**Comment by PeterC-DLS** [comment]
Hi Pierre,

As mentioned in the source, it is the shape of the sliced dataset. The slice iterator iterates over each point in the sliced dataset so the slice shape is the number of steps spanned in each dimension.

Regards,
Peter

**Comment by PierreSachot** [comment]
Dear Peter,

Thanks a lot for your quick reply, I would like to know an other thing about the start index and the stop index, is those about the dimensions or the values inside of the dimensions ?

Best regards,

Sachot Pierre.

**Comment by PeterC-DLS** [comment]
Hi Pierre,

These are the same as specified in Python and NumPy: start is inclusive and stop is exclusive. See also the Slice and SliceND classes.

Peter
