### ISSUE TITLE
Update .travis.yml on forms branch

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#164]
The current .travis.yml on the forms branch needs to be updated so that it builds.

AFAICT this means at least checking out the third-party tests.

This Issues is to go with status-quo, i.e. separate test repo. However #11 is still open and that is my preferred solution.

**Comment by PeterC-DLS** [comment]
Not relevant to this repo as january-form has moved to https://github.com/eclipse/january-forms/
