### ISSUE TITLE
LazyDatasetBase properties access fails in secure environment

### ISSUE THREAD

**Issue by scottslewis** [eclipse/january#172]
My environment is an OSGi framework impl running with the Java security manager...not Eclipse.

In LazyDatasetBase is this initialization code:

protected static boolean catchExceptions;
	
	static {
		/**
		 * Boolean to set to true if running jython scripts that utilise ScisoftPy in IDE
		 */
		catchExceptions = Boolean.getBoolean("run.in.eclipse");
}

This fails...and therefore the class cannot be loaded at all...in my environment where untrusted bundles are not allowed property access (via Boolean.getBoolean).   

You could follow the OSGi permissions structure, and put a permissions.perm file in META-INF, but that may be overkill given that catchExceptions doesn't look that critical.   You could also just set catchExceptions to false by default, and put a try/catch (Exception) block in the static initialized, so that this doesn't prevent the class from loading in such environments.

Thanks.

**Comment by PeterC-DLS** [comment]
Thanks for reporting the issue.
