### ISSUE TITLE
January p2 site missing some jars

### ISSUE THREAD

**Issue by mwebber** [eclipse/january#18]
The [p2 site](http://download.eclipse.org/january/releases/1.0.0/repository/) for January 1.0.0 is missing some bundles/features. Specifically, ones that I reference but are missing are:
`org.eclipse.january.asserts`
`org.eclipse.january.tests` (possibly not required)
(others might be missing as well; I didn't check)

**Comment by jonahkichwacoders** [comment]
Generally speaking I wouldn't have test bundles in main p2 repo, but rather in a test one. I assume that other tests (other than org.eclipse.january.tests) depends on o.e.j.asserts?

Adding the bundles under a test category in https://github.com/eclipse/january/blob/master/releng/org.eclipse.january.releng.p2/category.xml seems like a good balance between complexity and separation?

**Comment by mwebber** [comment]
You're quite right, some of our tests (in our own plugins) depend on `org.eclipse.january.asserts`.

My own preference is for just one p2 repo (rather than separate main and test ones) for bundles that belong to the same project, and have the same release cycle and versioning.

The p2 design means only components that are needed are downloaded, and in fact if the Eclipse instance already has the bundle/version it wants, it won't download it again. That's always been the case as I understand it, and with Oomph in Neon, there is further scope for bundle pooling between Eclipse instances. So having big p2 repos is not of itself a bad thing.

Your suggestion of having a test category (or maybe having january_datasets_test, january_form_test, january_geometry_test) sounds good.

One other thing - the one feature project org.eclipse.january.form.feature is not on the p2 site - should it be?

I would probably go for a single p2 site having artifacts for all the components in January. Anyhow, let me know what you think.

Thanks

**Comment by mwebber** [comment]
One other not particularly relevant note - there are really two use cases for a p2 repository.

One is providing components towards a target platform (that's my case).

The other is providing installable units (IUs) for a user to "Install New Software" into an existing Eclipse-based application. That's usually based around feature projects, and that's where the categories become important, since they govern what choices the user sees in the install dialog.

**Comment by jonahkichwacoders** [comment]
o.e.j.{asserts,test} added to p2 in 559405a955bc094b263913eaf2e851265d2b863a

The "latest" p2 site (http://download.eclipse.org/january/builds/january-master/latest/repository/) has the change. PS latest is only updated on stable builds (all tests passing).

Thanks for the other feedback. I am working on getting the list of bugs together to address various issues with o.e.j.{form,geometry} components. This will happen as part of the ICE/EAVP moving to pull from January as Dawn is doing.

Thanks!
