### ISSUE TITLE
Extraneous additional.bundles statements in build.properties files

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/january#2]
Some of the org.eclipse.january.geometry.* have dependencies listed as additional.bundles inside the build.properties files. These should instead be specified as Import-Packages in the manifest files.

**Comment by jonahkichwacoders** [comment]
Hi @SmithRWORNL, Thanks for the fixup. I am working on getting January to fully build and this helps along the way.

-- Jonah
