### ISSUE TITLE
Runtime error on running tutorial.

### ISSUE THREAD

**Issue by IanMayo** [eclipse/january#22]
I've encountered a runtime error with the tutorial class:

````
Exception in thread "main" java.lang.IllegalArgumentException: 
   New size is not same as the old size. Old size is 4 new size is 8 and shape is [8]
at org.eclipse.january.dataset.AbstractDataset.checkShape(AbstractDataset.java:579)
at org.eclipse.january.dataset.AbstractDataset.setShape(AbstractDataset.java:586)
at org.eclipse.january.dataset.DatasetFactory.createFromObject(DatasetFactory.java:318)
at org.eclipse.january.dataset.DatasetFactory.createFromObject(DatasetFactory.java:212)
at org.eclipse.january.dataset.DatasetFactory.createFromObject(DatasetFactory.java:171)
at org.eclipse.january.tutorial.C1TheBasics.doArrayCreation(C1TheBasics.java:58)
at org.eclipse.january.tutorial.C1TheBasics.main(C1TheBasics.java:93)
````
I've had to hack the repo structure around a little, since I've got a really poor mobile data signal - and I've had to just manually download the bare essential supporting libs.  So, the above problem may be self-inflicted - sorry if that's the case.  

But, I thought I'd share the problem nevertheless.  I'm running Eclipse-Neon on OSX, Java 1.8.0_112

**Comment by jonahkichwacoders** [comment]
Hi @IanMayo, I can confirm that I see the same thing.

@PeterC-DLS Is this tutorial a work in progress? Is the Exception here a bug in January or the tutorial?

Thanks.

**Comment by IanMayo** [comment]
@jonahkichwacoders - [here's](https://github.com/eclipse/january/blob/master/org.eclipse.january.examples/src/org/eclipse/january/tutorial/C1TheBasics.java#L58) the line at fault:
````
Dataset c = DatasetFactory.createFromObject(
    new int[][] {{2, 3}, {4, 5}}, Dataset.COMPLEX128);
`````

I suspect it may just be a problem in the tutorial, since this is the step where things get _complex_ (excuse the pun...).

**Comment by PeterC-DLS** [comment]
Ah, this is a bug in the example. It should be the dtype value first: as it is, that value is used as a shape.

Thanks for reporting it.
Peter

**Comment by PeterC-DLS** [comment]
Fix in #23

**Comment by IanMayo** [comment]
Great, thanks Peter.

Is this an argument for dType parameters being enums instead of int values? This would let the compiler/IDE prevent the occurrence of the above bug.  Or does the underlying implementation rely on special encoding of ARRAYMUL data-types?

````
static final int ARRAYMUL = 100;

/**
 * Array of signed 8-bit integers
 */
public static final int ARRAYINT8 = ARRAYMUL * INT8;
````

**Comment by gerring** [comment]
I have wondered from time to time why they are not enums. I think in numpy
they are also ints with the same value... There is probably some bit
shifting reason... Still we could have enums with the int as member data.

**Comment by jonahkichwacoders** [comment]
+1 for Enum in January. Enums don't really exist in Python. I'll create a new issue.

**Comment by PeterC-DLS** [comment]
No, NumPy allow several things to be dtype specifiers. In ScisoftPy (which @gerring may be referring to), we use the dtype class from NumPy in Python and our own class in Jython.

**Comment by gerring** [comment]
Looks like CORBA plus numpy synonymy means int is better?
