### ISSUE TITLE
Change dtype from int to enum

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#24]
In Bug #22 we discussed the idea of changing dtype from an int to enum. As that bug was closed, this new bug is to track further discussion/conclusions.

DatasetFactory.createFromObject() takes an int to specify datatype, this has limited static checking ability.

https://github.com/eclipse/january/blob/66dbbcbaa4f03ee1234203d56eb613d4348a1445/org.eclipse.january/src/org/eclipse/january/dataset/DatasetFactory.java#L198

**Comment by PeterC-DLS** [comment]
This was chosen as CORBA had issues with serialization/deserialization of enum and their equality.

**Comment by PeterC-DLS** [comment]
The better way is to eschew using the `dtype` and use the class-based methods in `DatasetFactory`. I will update the examples to show this...

**Comment by IanMayo** [comment]
That's a neat fix, @PeterC-DLS   Is it worth deprecating the methods that use the `dtype` parameter? Existing code would still work, but it would signal users towards the less hazardous version.

**Comment by jonahkichwacoders** [comment]
@PeterC-DLS AFAICT this issue is resolved by PR #60 and no new work is planned for this. Please re-open if I misunderstood.

**Comment by IanMayo** [comment]
@jonahkichwacoders - I wasn't aware of any discussion regarding the suggestion of deprecating the method(s) that caused the confusion.

I've submitted a PR with my suggested handling: #89   If that's satisfactory then I'll apply the change to the other methods, for subsequent review by yourself & @PeterC-DLS

**Comment by PeterC-DLS** [comment]
Looks fine to me, Ian. +2

**Comment by IanMayo** [comment]
Thanks for your support Peter, I'll apply it to the other methods.

**Comment by IanMayo** [comment]
Ok, after an embarrassing number of attempts I've successfully submitted a PR containing the remaining comments: https://github.com/eclipse/january/pull/92

**Comment by jonahkichwacoders** [comment]
Hi @IanMayo, Thanks for the deprecation comments, I think that really helps adopters a lot!

However, one side effect of the deprecation comments / annotations is that it has introduced hundreds of warnings in January's code base. I am not keen to change all those uses just before the 2.0 release, but I solicit comment on how not to have all these warnings now.

The options are:
1. Fix all the deprecation by using the new code.
2. In project settings lower deprecation from warning to info. As January has little external dependencies, it also has little that can be deprecated. IMHO this should be a temporary situation.
3. Annotate each use with Suppress warnings. Also IMHO a temporary solution, but one that naturally is resolved when the deprecated methods are removed.

(I have just seen that the per-project error/warning settings are not applied to January project. That is an oversight in itself AFAIK and I will raise that as a separate issue.)

**Comment by jonahkichwacoders** [comment]
Just to be clear, I think we can fix this after we branch for 2.0 this week.

**Comment by IanMayo** [comment]
Hmm, tricky one, @jonahkichwacoders 

My thoughts:
1.***Fix deprecation using new code***: could introduce fragility if there isn't lots of testing.  But there is a slim chance that these fixes could expose broken, rarely used code (like we found in #22, which triggered this conversation).
2. ***lower warning status***: is risk free - at least we're still guiding new adopters towards the safer methods
3. ***suppress warnings***: is more work, but it does mean the compiler is contributing to *push* users towards the safer methods. This use of `@Suppress` does seem within acceptable use -  you're suppressing errors on mature tested code, which is low risk.  Maintainers then (*post 2.0*) have a task of working through the suppressed calls and replacing them with the correct version.

I'm happy to invest some time in working through Option 3 today, if it's an acceptable strategy.  As with the `@Deprecated` changes - it doesn't represent change to functional code - so seems relatively risk-free.

I don't think I'll run out of time - should be 10s of minutes at the most.

@PeterC-DLS - any thoughts?

**Comment by PeterC-DLS** [comment]
Hi Ian,

I will be happy for you to work through option 3.

There are also new warnings from indirect access to static methods in GeneratedMaths – I’m undecided as yet what to do about this.

Regards,
Peter

**Comment by IanMayo** [comment]
@jonahkichwacoders - PR ready for review: #97

**Comment by PeterC-DLS** [comment]
Final updates to remove use of constants and deprecation suppression in #392 and #393
