### ISSUE TITLE
Port changes from org.eclipse.ice.datastructures

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/january#25]
We need to port over the changes from the latest version of the ICE project's org.eclipse.ice.datastructures to org.eclipse.january.form.

**Comment by jayjaybillings** [comment]
Very small changes, I'll add. We found a messed up extension point schema and a single missing file in build.properties for the form bundle.

We will port this change as we modify ICE to use January. We had to fix it in ICE because it was a critical bug.

**Comment by PeterC-DLS** [comment]
Closing as january-forms was moved to https://github.com/eclipse/january-forms
