### ISSUE TITLE
Code cleanup in Eclipse January

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january#26]
At the moment there are a few of issues in January that need to be resolved. This is an umbrella bug, individual issues can be split out of this bug, especially if they need discussion and are non-trivial.

These, therefore, make a list of my recommendations on how to improve January:

- Check-in generated xtend files so that contributors don't need xtend tooling unless they are editing those files. At the moment, checking out the entire project leads to lots of compiler errors.
- Remove UI code from January (January is a data project, the UI is contributed elsewhere)
- Remove example/demo Xtext code (there are a number of instances of classes in org.xtext.example.mydsl and sub-packages), for example [MyDsl.xtext](https://github.com/eclipse/january/blob/59ef32b3b062de97015d79f2eeb96a986b45fd4e/org.eclipse.january.geometry.xtext.vtk/src/org/xtext/example/mydsl/MyDsl.xtext) generates [AbstractMyDslRuntimeModule.java](https://github.com/eclipse/january/blob/59ef32b3b062de97015d79f2eeb96a986b45fd4e/org.eclipse.january.geometry.xtext.vtk/src-gen/org/xtext/example/mydsl/AbstractMyDslRuntimeModule.java) and many others
- At the moment the [README.md](https://github.com/eclipse/january/blob/59ef32b3b062de97015d79f2eeb96a986b45fd4e/README.md) only refers to the dataset part of January, as does the [examples](https://github.com/eclipse/january/tree/59ef32b3b062de97015d79f2eeb96a986b45fd4e/org.eclipse.january.examples). Therefore getting started for form and geometry is recommended.

**Comment by jonahkichwacoders** [comment]
Hi @jayjaybillings  and @SmithRWORNL, I have started my notes here on some improvements that can be made to January, Please feel free to cut these up into their own issues and deal with them as you see fit.

**Comment by PeterC-DLS** [comment]
Closing as january-forms was moved to https://github.com/eclipse/january-forms
