### ISSUE TITLE
access to dataset metadata not threadsafe

### ISSUE THREAD

**Issue by scottslewis** [eclipse/january#27]
The implementations of getMetadata(Class<T>) addMetadata(T)/setMetadata and any of the *Metdata methods on the LazyDatasetBase class do not have any synchronization around the access to the 'metadata' field...wrt creating the Map or accessing elements (getting and setting).  This means that the IDataset instances are not thread safe, and multithreaded access could result in non-deterministic NPEs or ConcurrentModification exceptions.

It would be helpful for some use cases to make LazyDatasetBase.*Metdata thread safe.

**Comment by PeterC-DLS** [comment]
Thanks for the issue. Yes, it should be though we haven't required it so far. Do you have time to fix this?

**Comment by gerring** [comment]
I we do this we should avoid putting synchronised methods and objects
everywhere because slowness of january is an issue already.

**Comment by jayjaybillings** [comment]
We avoid synchronized methods as much as possible in other projects and use Atomics instead. Some studies have shown them to be eight times faster than synchronized methods because they are implemented in hardware.


Jay Jay Billings
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by gerring** [comment]
Are Atomics things like ReetrantLock?

**Comment by jonahkichwacoders** [comment]
No, Atomics are their own thing, stuff in [java.util.concurrent.atomic](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/package-summary.html). Here is the article from Brian Geotz (author of Java Concurrency in Practice) from when the new feature was added in Java 5: http://www.ibm.com/developerworks/library/j-jtp11234/

**Comment by scottslewis** [comment]
Hi Matt.   Using synchronized keyword is essentially a Reentrant lock (in python threading lib terms).  You can also use the concurrent API (especially java 8), but my suggestion would be to use synchronized keyword in necessary places.   I would offer to provide a patch, but just can't at the moment.

**Comment by scottslewis** [comment]
I hadn't noticed discussion above...wrt synchronized keyword.   Although I agree that using synchronized in many locations is  bad, I don't think that is necessary to have many uses of synchronized to satisfy...rather just protecting the add/removal/lookup to the metadata storage (preventing ConcurrentModificationExceptions) is what we are looking for.

**Comment by gerring** [comment]
Scott and Jonah,

Thanks, duly noted, in a non-ironic way.

Matt

**Comment by jonahkichwacoders** [comment]
@PeterC-DLS PR #71 seems to have fixed this issue. Is there anything else left in this bug report that needs resolving?

**Comment by scottslewis** [comment]
My answer to Jonah is no...the fix in 71 looks good to me.  Thanks for the work.

**Comment by PeterC-DLS** [comment]
Done with merged PR
