### ISSUE TITLE
Reexport javax.measure.unit-api?

### ISSUE THREAD

**Issue by tschoonj** [eclipse/january#278]
When using the UnitMetadata class, I noticed getting a build path error for `javax.measure.Unit`. I fixed it by adding a bundle requirement for `javax.measure.unit-api`, but perhaps it would be better to reexport this bundle in the org.eclipse.january MANIFEST.MF?

**Comment by PeterC-DLS** [comment]
Yes, please!

**Comment by tschoonj** [comment]
Ok, will open PR
