### ISSUE TITLE
Can I import it in android studio?

### ISSUE THREAD

**Issue by SungmanHong** [eclipse/january#425]
I started App develop study in Android studio and learning java.

can I import this java package in android studio also? thx.

**Comment by PeterC-DLS** [comment]
Yes, you should be able to add it as a dependency (or jar). See, for example, https://search.maven.org/artifact/org.eclipse.january/org.eclipse.january

**Comment by SungmanHong** [comment]
Thanks, I'll close it!

**Comment by SungmanHong** [comment]
@PeterC-DLS 

I have one more questions...
I want to slice 4d float array but its really hard in JAVA....(very easy in python)

I found some solutions
https://stackoverflow.com/questions/16362872/how-to-get-2d-subarray-from-2d-array-in-java
and If this library also support multi dimensional array slicing as python method?

**Comment by PeterC-DLS** [comment]
There are two ways to slice multiple dimensions: directly using a `SliceND` object or with an array of `Slice` objects. So for `a`:
```
s1 = new SliceND(latents3.getShape());
s1.setSlice(0, 0, 1, 1);
s1.setSlice(3, 0, 1, 1);
a = latents3.getSlice(s1);
```
or
```
a = latents3.getSlice(new Slice(1), null, null, new Slice(1)); // null = select whole dimension
```
There's a variety of examples here: https://github.com/eclipse/january/blob/master/org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/SlicingExamples.java

**Comment by gerring** [comment]
👍

**Comment by SungmanHong** [comment]
Thank you very much! It'll really help to study and develop my app instead of python.
Thank you!!
