### ISSUE TITLE
Add January build

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/january#5]
This is to track in progress work. See our HIPP https://hudson.eclipse.org/january where builds are now running.

**Comment by jonahkichwacoders** [comment]
TODO list

- [ ] Resolve test failures (some/many are because of missing ICE test data)
- [ ] Publish results

**Comment by jayjaybillings** [comment]
All ICE test data is at github.com/jayjaybillings/ICETests

From my phone.
________________________________

**Comment by jonahkichwacoders** [comment]
January is now publishing builds: http://download.eclipse.org/january/builds/latest/repository/

At the moment we are promoting regardless of whether it is stable or not. Once the tests are at 0 we'll only promote stable builds.

**Comment by jonahkichwacoders** [comment]
Turns out that maven central cache is now on by default, no longer need manual settings for this one.

**Comment by jonahkichwacoders** [comment]
Hi Jay, The ICETests is currently a private repo. Previously you indicated that it is public, perhaps it has been made private again? 

From https://dev.eclipse.org/mhonarc/lists/january-dev/msg00013.html:

> As for the tests, that repo is now public: https://github.com/jayjaybillings/ICETests.

Thanks,
Jonah

**Comment by jayjaybillings** [comment]
Ah, okay. I apologize; I was wrong. I have to keep it private because of its history. Some of the files could not be distributed. We have removed them, but I need to clear the history. I'll look into it later today.

**Comment by jayjaybillings** [comment]
In the meantime, I have added you to the repo.

**Comment by jonahkichwacoders** [comment]
Thanks Jay.

**Comment by jonahkichwacoders** [comment]
> We have removed them, but I need to clear the history. I'll look into it later today.

Can we just take the contents of the head commit and stick that in a new repo? 

Also, I think it is critical to get the test code into the January repo to make it maintainable and make it possible to contribute with as few barriers as possible. That means either recreating test code that has copyright issues, or getting the test code through a CQ.

**Comment by jonahkichwacoders** [comment]
Not java code, but stuff under problematic copyright. This is the comment I was "replying" to from [january-dev](https://dev.eclipse.org/mhonarc/lists/january-dev/msg00013.html)

> However, they are not allowed to be stored in any Eclipse repo because the IP is worried about copyright infringement. We are allowed to use them on the build servers, but not distribute them. Once upon a time these were stored in each test folder, which was very nice, but we had to move them out because of the IP concerns.

**Comment by jayjaybillings** [comment]
I hit send a bit too quickly. My plan is to create a new repo, yes. Of course, you can do that if you want since you have access now.

We also cannot put these directly in project repositories because some of them may include copyrighted content from 3rd parties. The IP team advised us to use a separate repo.

**Comment by jayjaybillings** [comment]
Yes, that's email is still true. So we just have to keep them in a separate repo.

**Comment by jonahkichwacoders** [comment]
OK, I will review them and come up with a suggestion to get past IP issues. Having a separate repo is far from ideal going forward and puts unnecessary constraints on contributors. 

I appreciate the push permissions, but I won't be using them for ICETests. If the current HEAD of ICETests can be in a public repo I can create a new repo for January (e.g. JanuaryTessts) and then start trimming out what isn't needed. All that with a goal of deprecating that repo and getting it back in january.

CQ 8577 talks about discussions that were not added to the CQ regarding needing workswith CQ for the test data, I couldn't find whether that CQ has been raised for ICE, but to get January to release we need to do one of these (or a mixture):

- do the workswith CQ
- contribute the test data (resolving copyright issues)
- replace the test data with IP clean tests
- remove tests relying on the test data

**Comment by jayjaybillings** [comment]
@jonahkichwacoders I think you will only need the datastructuresData folder from that repo. You might also need the CSVVizService directory for EAVP. @SmithRWORNL can tell us. Most of the xml files in that data directory are released into the public domain, which has various legal problems in the rest of the world and probably won't make it through the Eclipse process. For example, several of the XSDs were released by NIST.

Our testing situation was discussed as part of our IC CQ.

Please keep in mind though that you don't need these for a January release, only development work. In general no release should come with test files You never see a file like "org.eclipse.january.forms.test" in a p2 repo, right? Instead, we release only the functional jars and hold back the tests.

Please take what I say next with a grain of salt or as merely a note of preference, not as me throwing down a gauntlet: If you remove the tests relying on the test data, then ICE and EAVP won't be moving January until some replacement for those tests is in place. We can't afford to go test-less on our code. It is very easy and relatively painless to add these to the build, especially once they are in a public repo, so I'll do it if you want and we can worry about cleaning them up later. Just let me know.

**Comment by jonahkichwacoders** [comment]
Removing tests is the last thing I want to do. But my interest in being project lead on this project is making these excellent reusable components reusable outside of ICE and DAWNSci. For this to work we need tests and test data. That means that things like "mvn verify" should *just work*. 

BTW I will not be making any code or test changes to anything in January without relevant review by ORNL or Diamond teams. I am just trying to get it to a release now and make it available and reusable. 

> Our testing situation was discussed as part of our IC CQ.

Sadly the discussion was not made part of the CQ but rather only the conclusions.

**Comment by jonahkichwacoders** [comment]
> Please keep in mind though that you don't need these for a January release, only development work. In general no release should come with test files You never see a file like "org.eclipse.january.forms.test" in a p2 repo, right? Instead, we release only the functional jars and hold back the tests.

Yes, the tests are not part of any release/p2 repo.

**Comment by jayjaybillings** [comment]
Sorry, I meant the ICE testing situation was discussed as part of the ICE IC CQ.

I agree that "mvn verify" should just work, but I'm not sure of the best way to do that when I/O comes into the picture, and especially if that I/O involves testing real examples from the wild. I'm open to however you want to fix it, but I'm just saying that it may be a bridge that we choose to cross at a later time.

I wonder if, as a temporary work around, we can get mvn verify to do a git clone of a january-tests GitHub repo?

**Comment by jonahkichwacoders** [comment]
The temporary workaround will be to continue to do what ICE does and check out the additional repo. I agree it does not have to be before the October release.

**Comment by jonahkichwacoders** [comment]
> Sorry, I meant the ICE testing situation was discussed as part of the ICE IC CQ.

Do you still have the record of that to save me asking questions already discussed. The ICE IC CQ is 8577 and does not AFAICT have the discussion but rather the conclusions. The conclusion ([comment 9](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=8577#c9)) makes reference to emails that are not included.

Anyway, I am part of the way through the review of what is actually used from ICETests and it is fortunately rather minimal. More on that soon.

**Comment by jayjaybillings** [comment]
The first bullet in Comment 9 is most of the discussion:

> 
Build and Test Requirements not to be checked into the repository.  Only to
be utilized via the Build and Test Server for Ice.  The Project will need to
raise a Workswith CQ to cover this in the near future.

The emails just said "these are the test files."

I'm glad I looked over this though... looks like I need to submit a works-with CQ...

**Comment by jayjaybillings** [comment]
I raise a bug for the workswith CQ for ICE. I'll post the CQ there when I submit it. https://github.com/eclipse/ice/issues/266

**Comment by SmithRWORNL** [comment]
@jayjaybillings It looks like we need the datastructuresData and itemData folders from ICETests.

**Comment by jonahkichwacoders** [comment]
We have a green light for January. All tests pass, but there are a few caveats that will be resolved in other bugs.
