### ISSUE TITLE
org.eclipse.january.geometry.xtext.vtk bundles are mislabelled

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/january#57]
The org.eclipse.january.geometry.xtext.vtk bundles are mislabelled, which leads to some very nasty code and names like "MyDSLRuntimeModule.xtend." This needs to be cleaned up.

**Comment by jayjaybillings** [comment]
org.eclipse.january.geometry.ide is also mislabeled since it is really the bundle that has all of our STL support.

**Comment by PeterC-DLS** [comment]
Closing as january-forms was moved to https://github.com/eclipse/january-forms
