### ISSUE TITLE
Copyright of BasicExample

### ISSUE THREAD

**Issue by gerring** [eclipse/january#70]
Is the copyright of BasicExample correct at:

https://github.com/eclipse/january/blob/master/org.eclipse.january.examples/src/org/eclipse/january/examples/dataset/BasicExample.java

at Kichwa? :)

If DLS have paid for the work, we retain copyright but release open source.

Cheerio,

Matt

**Comment by tracymiranda** [comment]
The copyright is correct. As is your assertion.

Tracy
