### ISSUE TITLE
Add unit metadata

### ISSUE THREAD

**Issue by PeterC-DLS** [eclipse/january#72]
Using UoM's [unit-api](https://github.com/unitsofmeasurement/unit-api)

**Comment by jonahkichwacoders** [comment]
This announcement may be relevant? https://dev.eclipse.org/mhonarc/lists/science-iwg/msg02359.html

**Comment by PeterC-DLS** [comment]
We need the NonSI class here at Diamond (mainly for units of Angstroms). I don't think [uom-se](https://github.com/unitsofmeasurement/uom-se) contains that whereas [si-units](https://github.com/unitsofmeasurement/si-units) does but it has not been released.

**Comment by IanMayo** [comment]
Guys, I remain willing to explore this capability, with the aim of (optionally) making `Dataset` units-aware, in the spirit of generally encouraging good science.

But, I lack the skills to navigate the IP minefield.  If the January team is able to produce a branch that includes/references the UoM libraries necessary to support the following imports, then I'm happy to run with it:
```` java
import org.eclipse.uomo.units.SI;
import org.unitsofmeasurement.unit.Unit;
````

**Comment by PeterC-DLS** [comment]
Hi Ian,

I was putting off adding the unit metadata to January as we (at DLS) have a requirement to support units of Angstroms. Since the 0.6.3 release of si-units last month has added this, I will revisit this shortly.

Regards,
Peter

**Comment by IanMayo** [comment]
Good afternoon Peter,
that would be great, thank you.  

I will be able to carry on investigating models for supporting UoM in January using a development fork, but will only be able to submit PR(s) for review/discussion once I can build using the formal libs.
Thanks,
Ian
